### ISSUE TITLE
Unselect a selected toggle button in a group of toggle buttons

### ISSUE THREAD

**Issue by llavayssiere** [ianharrigan/haxeui#223] opened 2015-03-16 21:28 UTC
In a group of toggle buttons, it must not be possible to set a selected toggle button to (selected = false) if all other toggle buttons are also set to (selected = false).

Proposed corrected code for set_selected function for button.hx file :

	private function set_selected(value:Bool):Bool {
		if (_toggle == true && _selected != value) {
			// If toggle button state has changed, 
			// unselect other buttons in the same group
			if (_group != null) {
				var arr:Array<Button> = _groups.get(_group);
				if (arr != null) {
					if (value == true) {
						// In the same group, if a toggle button is set to (selected = true)
						// all other toggle buttons must be set to (selected = false)						
						_selected = value;
						for (button in arr) {
							if (button != this) {
								button.selected = false;
							}
						}
					} else {
						// In the same group, it must not be possible to set a toggle button to (selected = false) if 
						// all other toggle buttons are set to (selected = false)
						var isAllFalse:Bool = true;
						for (button in arr) {
							if (button != this) {
								isAllFalse = isAllFalse && (button.selected == false);
							}
						}
						if (isAllFalse) {
							return value;
						}
						_selected = value;
					}
				} else {
					_selected = value;
				}
			} else {
				_selected = value;				
			}				
		} else {
			_selected = value;			
		}
		
		if (dispatchChangeEvents == true) {
			var event:UIEvent = new UIEvent(UIEvent.CHANGE);
			dispatchEvent(event);
		}				

		if (_selected == true) {
			state = STATE_DOWN;
		} else {
			#if !(android)
				if (root != null && hitTest(root.mousePosition.x, root.mousePosition.y) == true) {
					state = STATE_OVER;
				} else {
					state = STATE_NORMAL;
				}
			#else
				state = STATE_NORMAL;
			#end
		}
			
		return value;
	}

**Comment by ianharrigan** [comment] 2015-03-17 22:15
Cool. Nice one thanks. Im in London for another 2 days then I'll review and merge. Thanks again.

**Comment by ianharrigan** [comment] 2015-03-21 11:54
So, let me get this right... The issue is that if you have a set of radio buttons and one is selected, then you shouldnt be able to set the selected one to false, in code... is that accurate? Ie, this is only about setting from code... If you click on the selected item i presume it doesnt unselect it, is that right?

Cheers,
Ian

**Comment by llavayssiere** [comment] 2015-03-21 17:50
Yes. Exact.You can see the modified code in action here for the 4 grouped toggle buttons "1", "2", "3" and "4". : http://www.neoviz.fr/index.php/en/demos/cac40admin. Select a node of the network and select/unselect one of the grouped toggle buttons to see the result.

**Comment by ianharrigan** [comment] 2015-03-21 18:40
Ok, great... Ill integrate the code shortly...

Cheers!
Ian

**Comment by ianharrigan** [comment] 2015-03-21 18:45
(cool app btw!)

**Comment by ianharrigan** [comment] 2015-03-21 19:17
I wonder if there is a simpler way to do this... Im just setting up a test to reproduce the issue, but i kinda feel like this could be a much simpler fix.

**Comment by llavayssiere** [comment] 2015-03-21 19:26
HaxeUI is great but i don't know your library as better than you. So i think you will find a simpler fix !

**Comment by ianharrigan** [comment] 2015-03-21 19:31
Cool... Looking at it now... I understand the problem completely (i think) so will see what type of fix i come up with... It may very we be similar to yours above. Either way, thanks loads for the pointer and code... Ill close this issue shortly!

Cheers!
Ian

**Comment by ianharrigan** [comment] 2015-03-21 20:14
... ... after thinking about it a little, is there ever a case when you can set an option box to false from code if it has a group? Would it you not just set one to true?

**Comment by llavayssiere** [comment] 2015-03-22 14:57
No other case i think. Yes, in a group of toggle buttons, just one toggle button must be set to true and  It would never be possible to set all buttons to false. After all, the behaviour of a group of toggle buttons is like a group of radio buttons, this is the only interest to group toggle buttons i think.

**Comment by ianharrigan** [comment] 2015-03-23 01:02
Ok, I think i have fixed this, its in haxelib (version 1.7.4)... Could you test and close this issue if it works?

Thanks again,
Ian

**Comment by ianharrigan** [comment] 2015-03-30 08:41
@llavayssiere - any idea whether this fixes it or not? Wondering of that can be closed.

Cheers,
Ian

**Comment by llavayssiere** [comment] 2015-03-31 09:55
I will check this week to close this issue.

**Comment by ianharrigan** [comment] 2015-03-31 10:08
Thats great... Thanks loads!

Ian

**Comment by llavayssiere** [comment] 2015-03-31 20:22
Tested with haxeui version 1.7.6 and it works !
Thank you for this new version.

**Comment by ianharrigan** [comment] 2015-04-01 08:27
Great! Thanks again for finding this out and the code sample, etc. All much appreciated!

Cheers,
Ian

**Closed by ianharrigan** 2015-04-01 08:27 UTC
Labels: bug, in progress
