### ISSUE TITLE
UIEvent.CLICK is still dispatched for disabled buttons.

### ISSUE THREAD

**Issue by tiagolr** [ianharrigan/haxeui#142] opened 2014-08-20 16:36 UTC
Somehow this happens, while implementing back in forward buttons on haxeui-file-dialogs, if i go forward and backward a couple of times, the back buttons will then still fire the CLICK event even tho it is disabled (causing the app to crash cause there is nothing to go back to).

I haven't been able to debug properly since i run this on Neko/cpp, but a simple trace (besides the grayed button appearance) shows that the button is disabled when the click callback is called.

**Comment by marcelofrau** [comment] 2015-03-23 14:06
Later today I'll make some tests on this and if we need to fix somethin I'll make the fix and close this issue.

**Comment by ianharrigan** [comment] 2015-03-23 14:09
Great! As noted above, i tried a few times and couldnt reproduce.

Cheers,
Ian

**Comment by sebthom** [comment] 2015-11-26 23:57
I believe this is fixed with #307

**Closed** 2015-12-19 02:06 UTC
Labels: in progress, retest required
