### ISSUE TITLE
Can't compile for native targets using Haxe 3.2.1

### ISSUE THREAD

**Issue by ex** [ianharrigan/haxeui#282] opened 2015-10-23 22:30 UTC
I'm not sure if the haxeui library needs to be updated or it's a Haxe regresion bug, but after upgrading  to the latest Haxe 3.2.1 version, a previously working project fails to compile with compiler errors in the generated C++ code. Can you confirm?

**Comment by ianharrigan** [comment] 2015-10-24 09:14
Hi, ill try a little later today (i havent upgraded haxe yet), do you have a little more info? What errors are you getting? What version of openfl, lime, etc? Does neko or flash work?

Cheers,
Ian

**Comment by bendmorris** [comment] 2015-10-24 18:37
Not sure if these are the same issues as @ex but I've been struggling to get this working in C++ as well.

First, 3.2.1 resulted in this error:

    Error: ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:161:15: error: allocating an object of abstract class type '::haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_<ItemRenderer_obj>'
        { return new ::haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_< ItemRenderer_obj >(this); }
                     ^

I think this is related to this issue: https://github.com/HaxeFoundation/hxcpp/issues/314

There is a fix for this in the development branch of Haxe. However this version causes a separate issue:

    src-client/chomper/ui/LoginPopup.hx:44: characters 3-16 : haxe.ui.toolkit.core.Root has no field onResize
    src-client/chomper/ui/LoginPopup.hx:44: characters 19-30 : haxe.ui.toolkit.containers.Absolute has no field onReady
    src-client/chomper/ui/LoginPopup.hx:105: characters 3-19 : haxe.ui.toolkit.controls.Button has no field onClick
    src-client/chomper/ui/GameOverPopup.hx:44: characters 3-16 : haxe.ui.toolkit.core.Root has no field onResize
    src-client/chomper/ui/GameOverPopup.hx:44: characters 19-30 : haxe.ui.toolkit.containers.Absolute has no field onReady
    src-client/chomper/ui/GameOverPopup.hx:84: characters 3-19 : haxe.ui.toolkit.controls.Button has no field onClick

It seems like the build macro for DisplayObject is not being run, so DisplayObjects no longer support any events.

These seem like issues with Haxe and not HaxeUI, but I haven't been able to reproduce the build macro not running issue with any simple test projects not using HaxeUI.

**Comment by bendmorris** [comment] 2015-10-24 18:50
I reported this separately in the Haxe repo: https://github.com/HaxeFoundation/haxe/issues/4607

**Comment by ianharrigan** [comment] 2015-10-24 19:16
Hmm, thats not good. So when you say you havent been able to reproduce this in non-haxeui apps, do you mean that in a simple test app, @build and @autoBuild behave as expected with haxe 3.2.1?

**Comment by bendmorris** [comment] 2015-10-24 19:18
Now I realize the issue is multiple build macros (https://github.com/HaxeFoundation/haxe/issues/4454) and was able to reproduce a simple test case.

**Comment by ianharrigan** [comment] 2015-10-24 19:23
Ok, well, at least it seems like its a known issue. I guess the best thing to do is wait for a patch for haxe? A little worrying none-the-less, as you note, this type of thing will break haxeui all over the place.

**Comment by ex** [comment] 2015-10-26 15:24
@bendmorris it's the same issue.
@ianharrigan it's something that we need to fix on the macros with Haxe 3.3.0? or it is a Haxe bug?

**Comment by ianharrigan** [comment] 2015-10-26 15:26
As far as i understand from the linked issues its a haxe bug, ie, if there are 2 (or presumably more) build macros then only the last gets run. Thats my understanding at least.

**Comment by fullofcaffeine** [comment] 2015-10-28 21:53
Is this being tracked as an issue on the `haxe` repo?

**Comment by fullofcaffeine** [comment] 2015-10-28 21:54
Oh, I see the links now.

**Comment by hopewise** [comment] 2015-11-02 03:59
@fullofcaffeine any update?

**Comment by ianharrigan** [comment] 2015-11-04 06:01
I think the best thing to do is to downgrade to haxe 3.2.0 and see if that fixes the problem, thats what im running here and all seems fine

**Comment by MSGhero** [comment] 2015-11-20 02:49
:+1: the haxe issue was fixed today on git

**Comment by ianharrigan** [comment] 2015-11-20 11:36
Does that mean its not happening anymore with git haxe?

**Comment by MSGhero** [comment] 2015-11-20 14:51
Git haxe has other issues preventing compiles, but the multiple build macro part was fixed. I can't confirm since I can't compile, but the issue was closed.

**Comment by ianharrigan** [comment] 2015-11-22 13:36
Btw, ive got confirmation from another person that downgrading to haxe 3.2.0 allows compilation on mac

**Comment by ianharrigan** [comment] 2016-01-22 11:26
Can you try with the latest version of haxeui `1.8.5` - it should be fixed there now.

**Comment by ex** [comment] 2016-02-22 20:46
I tried with latest nightly build of Haxe, and this build error is not happening, unfortunately there are other build errors with my project in that version so it's not usable and the fixes were not backported to 3.2.1. So in this case there is no other option that await for stable 3.3.0 and keep using haxe 3.2.0 or use a custom haxe with only the fixes required to compile haxeui.

**Comment by MSGhero** [comment] 2016-02-22 22:57
There are breaking changes between 3.3.0 and 3.2.1 :)

**Comment by NemoStein** [comment] 2016-02-27 22:34
@ianharrigan I'm having some trouble making this workout on lime cpp targets (Windows and Android). Please, take a look at this comment on Lime issue tracker: https://github.com/openfl/lime/issues/559#issuecomment-189739683

Downgrading Haxe to 3.2.0 didn't make it.
I'm currently using HaxeUI 1.8.17

**Comment by ianharrigan** [comment] 2016-02-28 06:03
Right, yeah. Currently HaxeUI (v1) requires legacy openfl

**Comment by ex** [comment] 2016-05-18 22:24
I just tested this again in a simple demo with Haxe 3.2.1 and github haxeui and can confirm my demo is working. Demo link: https://github.com/ex/haxe/tree/master/haxeui

**Closed** 2016-05-18 22:24 UTC
